### ISSUE TITLE
Version 1.2.1 and "ValueError: Cannot assign None: "Foo.bar" does not allow null values."

### ISSUE THREAD

**Issue by GermanoGuerrini** [vandersonmota/model_mommy#171] opened 2014-07-10 09:41 UTC
I have been using version 1.2 for a while without a problem, but since I installed 1.2.1 I started to get a lot of `ValueError` as the one you see above.
Basically, it looks like that when mommy creates a `ManyToManyField` for a model it's not able to relate it to the instance being created.

An example will help me explain it:
this worked with version 1.2 (simplified):

        tag1 = mommy.make_recipe('myapp.TagRecipe')
        tag2 = mommy.make_recipe('myapp.TagRecipe')
        tag3 = mommy.make_recipe('myapp.TagRecipe')
        params = {
            'tags': [tag1, tag2, tag3],
        }
        article = mommy.make_recipe("myapp.ArticleRecipe", **params)

The recipes simply being:

    TagRecipe = Recipe(Tag, name = seq('tag'))
    ArticleRecipe = Recipe(Article, name = seq('article'))

And the models:

    class Tag(models.Model):
         name = models.CharField(max_length=255, unique=True)
         [...]

    class Article(models.Model):
        name = models.CharField(max_length=255, unique=True)
        tags = models.ManyToManyField(Tag, related_name="articles", blank=True, null=True)
        [...]

Since version 1.2.1 I'm getting:

    ValueError: Cannot assign None: "Article_tags.article" does not allow null values.

If you need more information I'll be happy to provide it.

**Comment by berinhard** [comment] 2015-05-23 19:47
@GermanoGuerrini we couldn't reproduce this error. Does it still happen?  Any updates on this issue?

**Comment by romulocollopy** [comment] 2015-05-24 22:10
@GermanoGuerrini, could you provide us a failing test?

**Comment by GermanoGuerrini** [comment] 2015-05-25 06:33
Hello,
I'm not working any longer on the project that gave me that error.
I'll see if I can resume it and let you know asap.

**Comment by vandersonmota** [comment] 2015-07-25 19:45
@GermanoGuerrini Closing it for now. Feel free to reopen when/if you have new info.

[]'s

**Closed by vandersonmota** 2015-07-25 19:45 UTC
